### ISSUE TITLE
frontend & pushing the app on server

### ISSUE THREAD

**Issue by parth721** [zenmonks/hack1#12]
- [x] #13
     - [ ]  minimum 3 output slot with info from which group  
- [ ] how to upload it on server (heruko)

extra : 
- [ ] SEO optimization

**Comment by Diprajpaul1** [comment]
bro i have just doing the django project so give me tomorrow to make full website with a database as u mentioned ,,,, its now 1.30am so i am fully tired so give me tomorrpw to complete the django project and then i will give u what u have to want........
